
# Screen properties
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT

# Render properties
RENDER_SCALE = 0.45
RENDER_WIDTH = SCREEN_WIDTH * RENDER_SCALE
RENDER_HEIGHT = SCREEN_HEIGHT * RENDER_SCALE
RENDER_SIZE = RENDER_WIDTH, RENDER_HEIGHT

# Physics properties
PHYS_GRAVITY = -750
PHYS_JUMP_POWER = 300
PHYS_WALK_SPEED = 64
PHYS_RUN_SPEED = 128

# Tilemap Properties
TILE_SCALE = 2.3
