
# Render properties
RENDER_WIDTH = 400
RENDER_HEIGHT = 300
RENDER_SIZE = RENDER_WIDTH, RENDER_HEIGHT
RENDER_SCALE = 2

# Screen properties
SCREEN_WIDTH = RENDER_WIDTH * RENDER_SCALE
SCREEN_HEIGHT = RENDER_HEIGHT * RENDER_SCALE
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT

# Physics properties
PHYS_GRAVITY = -750
PHYS_JUMP_POWER = 300
PHYS_WALK_SPEED = 64
PHYS_RUN_SPEED = 128

# Tilemap Properties
TILE_SCALE = 2.3
