
# Screen properties    
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT

# Physics properties
PHYS_GRAVITY = -450
PHYS_JUMP_POWER = 250
PHYS_WALK_SPEED = 64
PHYS_RUN_SPEED = 128

# Tilemap Properties
TILE_SCALE = 2.3
