
# Screen properties    
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT

# Physics properties
PHYS_GRAVITY = -9.8
PHYS_JUMP_POWER = 5
PHYS_WALK_SPEED = 1.3
PHYS_RUN_SPEED = 2.6
